# This workflow will build an Android project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI with Gradle

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Cache gradle dependencies
      uses: actions/cache@v2.1.4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      run: chmod +x android_app/gradlew
    - name: Build with Gradle
      run: |
        cd android_app
        ./gradlew build --no-daemon --stacktrace
      env:
        GH_USER: ${{ secrets.GH_USER }}
        GH_PACKAGES_READ: ${{ secrets.GH_PACKAGES_READ }}
    - name: Upload results from lint tests
      uses: actions/upload-artifact@v2
      with:
        name: Lint reports
        path: android_app/app/build/reports/
    - name: Upload mapping files
      uses: actions/upload-artifact@v2
      with:
        name: Mappings
        path: android_app/app/build/outputs/mapping/
    - name: Upload compiled app APKs
      uses: actions/upload-artifact@v2
      with:
        name: APKs
        path: android_app/app/build/outputs/apk/
    - name: Cleanup Gradle cache
      # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
      # Restoring these files from a GitHub Actions cache might cause problems for future builds.
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties